-- The items schema as versioned code. One file for both run modes:
-- H2 (native dev and tests) and PostgreSQL (compose). Flyway runs this
-- once per database and tracks it in flyway_schema_history.

CREATE TABLE items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);